name: Build Angular Frontend

on:
  push:
    branches:
      - master  # or 'main' if your default branch is named that

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci  # or npm install
        working-directory: ./  # Adjust if your Angular project is in a subfolder

      - name: Build Angular app
        run: |
          npm run build -- --prod
        working-directory: ./  # Adjust path if Angular project is inside a folder
